// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: api/registerWorker.proto

package registerWorker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 注册工作进程
type RegisterWorker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 服务编号，取值范围是 1~999,业务层可以自己随意安排
	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *RegisterWorker) Reset() {
	*x = RegisterWorker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_registerWorker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterWorker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorker) ProtoMessage() {}

func (x *RegisterWorker) ProtoReflect() protoreflect.Message {
	mi := &file_api_registerWorker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorker.ProtoReflect.Descriptor instead.
func (*RegisterWorker) Descriptor() ([]byte, []int) {
	return file_api_registerWorker_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterWorker) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_api_registerWorker_proto protoreflect.FileDescriptor

var file_api_registerWorker_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x0e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x42, 0x2a, 0x5a, 0x28,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x3b, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_registerWorker_proto_rawDescOnce sync.Once
	file_api_registerWorker_proto_rawDescData = file_api_registerWorker_proto_rawDesc
)

func file_api_registerWorker_proto_rawDescGZIP() []byte {
	file_api_registerWorker_proto_rawDescOnce.Do(func() {
		file_api_registerWorker_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_registerWorker_proto_rawDescData)
	})
	return file_api_registerWorker_proto_rawDescData
}

var file_api_registerWorker_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_registerWorker_proto_goTypes = []interface{}{
	(*RegisterWorker)(nil), // 0: RegisterWorker
}
var file_api_registerWorker_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_registerWorker_proto_init() }
func file_api_registerWorker_proto_init() {
	if File_api_registerWorker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_registerWorker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterWorker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_registerWorker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_registerWorker_proto_goTypes,
		DependencyIndexes: file_api_registerWorker_proto_depIdxs,
		MessageInfos:      file_api_registerWorker_proto_msgTypes,
	}.Build()
	File_api_registerWorker_proto = out.File
	file_api_registerWorker_proto_rawDesc = nil
	file_api_registerWorker_proto_goTypes = nil
	file_api_registerWorker_proto_depIdxs = nil
}
