// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: toWorker/respSessionInfo.proto

package respSessionInfo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 返回session信息到工作进程
type RespSessionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 自定义的cmd，网关会原样回传给工作进程
	Cmd int32 `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	// 当前连接的id
	SessionId uint32 `protobuf:"varint,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	// 用户登录后存储在网关中的信息
	User string `protobuf:"bytes,3,opt,name=User,proto3" json:"User,omitempty"`
	// 用户是否登录成功
	LoginStatus bool `protobuf:"varint,4,opt,name=loginStatus,proto3" json:"loginStatus,omitempty"`
	// 用户订阅的主题
	Topics []string `protobuf:"bytes,5,rep,name=topics,proto3" json:"topics,omitempty"`
}

func (x *RespSessionInfo) Reset() {
	*x = RespSessionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toWorker_respSessionInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespSessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespSessionInfo) ProtoMessage() {}

func (x *RespSessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_toWorker_respSessionInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespSessionInfo.ProtoReflect.Descriptor instead.
func (*RespSessionInfo) Descriptor() ([]byte, []int) {
	return file_toWorker_respSessionInfo_proto_rawDescGZIP(), []int{0}
}

func (x *RespSessionInfo) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *RespSessionInfo) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *RespSessionInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RespSessionInfo) GetLoginStatus() bool {
	if x != nil {
		return x.LoginStatus
	}
	return false
}

func (x *RespSessionInfo) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

var File_toWorker_respSessionInfo_proto protoreflect.FileDescriptor

var file_toWorker_respSessionInfo_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x74, 0x6f, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x74, 0x6f, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x22, 0x8f, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x73, 0x42, 0x35, 0x5a, 0x33, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2f, 0x74, 0x6f, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x73, 0x70,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x3b, 0x72, 0x65, 0x73, 0x70,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_toWorker_respSessionInfo_proto_rawDescOnce sync.Once
	file_toWorker_respSessionInfo_proto_rawDescData = file_toWorker_respSessionInfo_proto_rawDesc
)

func file_toWorker_respSessionInfo_proto_rawDescGZIP() []byte {
	file_toWorker_respSessionInfo_proto_rawDescOnce.Do(func() {
		file_toWorker_respSessionInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_toWorker_respSessionInfo_proto_rawDescData)
	})
	return file_toWorker_respSessionInfo_proto_rawDescData
}

var file_toWorker_respSessionInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_toWorker_respSessionInfo_proto_goTypes = []interface{}{
	(*RespSessionInfo)(nil), // 0: toWorkerTransfer.RespSessionInfo
}
var file_toWorker_respSessionInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_toWorker_respSessionInfo_proto_init() }
func file_toWorker_respSessionInfo_proto_init() {
	if File_toWorker_respSessionInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_toWorker_respSessionInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespSessionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_toWorker_respSessionInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_toWorker_respSessionInfo_proto_goTypes,
		DependencyIndexes: file_toWorker_respSessionInfo_proto_depIdxs,
		MessageInfos:      file_toWorker_respSessionInfo_proto_msgTypes,
	}.Build()
	File_toWorker_respSessionInfo_proto = out.File
	file_toWorker_respSessionInfo_proto_rawDesc = nil
	file_toWorker_respSessionInfo_proto_goTypes = nil
	file_toWorker_respSessionInfo_proto_depIdxs = nil
}
