// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: toServer/reqTopicsSessionId.proto

package reqTopicsSessionId

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reCtx "netsvr/internal/protocol/reCtx"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取网关中的某几个主题的session id
type ReqTopicsSessionId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 请求上下文，网关会原样回传给工作进程
	ReCtx *reCtx.ReCtx `protobuf:"bytes,1,opt,name=reCtx,proto3" json:"reCtx,omitempty"`
	// 主题集合
	Topics []string `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
}

func (x *ReqTopicsSessionId) Reset() {
	*x = ReqTopicsSessionId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toServer_reqTopicsSessionId_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqTopicsSessionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqTopicsSessionId) ProtoMessage() {}

func (x *ReqTopicsSessionId) ProtoReflect() protoreflect.Message {
	mi := &file_toServer_reqTopicsSessionId_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqTopicsSessionId.ProtoReflect.Descriptor instead.
func (*ReqTopicsSessionId) Descriptor() ([]byte, []int) {
	return file_toServer_reqTopicsSessionId_proto_rawDescGZIP(), []int{0}
}

func (x *ReqTopicsSessionId) GetReCtx() *reCtx.ReCtx {
	if x != nil {
		return x.ReCtx
	}
	return nil
}

func (x *ReqTopicsSessionId) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

var File_toServer_reqTopicsSessionId_proto protoreflect.FileDescriptor

var file_toServer_reqTopicsSessionId_proto_rawDesc = []byte{
	0x0a, 0x21, 0x74, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x71, 0x54, 0x6f,
	0x70, 0x69, 0x63, 0x73, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x11, 0x74, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x1a, 0x11, 0x72, 0x65, 0x43, 0x74, 0x78, 0x2f, 0x72, 0x65,
	0x43, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x12, 0x52, 0x65, 0x71,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x22, 0x0a, 0x05, 0x72, 0x65, 0x43, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x72, 0x65, 0x43, 0x74, 0x78, 0x2e, 0x52, 0x65, 0x43, 0x74, 0x78, 0x52, 0x05, 0x72, 0x65,
	0x43, 0x74, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x42, 0x49, 0x5a, 0x47, 0x6e,
	0x65, 0x74, 0x73, 0x76, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x74, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x72, 0x65, 0x71, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x3b, 0x72, 0x65, 0x71, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_toServer_reqTopicsSessionId_proto_rawDescOnce sync.Once
	file_toServer_reqTopicsSessionId_proto_rawDescData = file_toServer_reqTopicsSessionId_proto_rawDesc
)

func file_toServer_reqTopicsSessionId_proto_rawDescGZIP() []byte {
	file_toServer_reqTopicsSessionId_proto_rawDescOnce.Do(func() {
		file_toServer_reqTopicsSessionId_proto_rawDescData = protoimpl.X.CompressGZIP(file_toServer_reqTopicsSessionId_proto_rawDescData)
	})
	return file_toServer_reqTopicsSessionId_proto_rawDescData
}

var file_toServer_reqTopicsSessionId_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_toServer_reqTopicsSessionId_proto_goTypes = []interface{}{
	(*ReqTopicsSessionId)(nil), // 0: toServerSubscribe.ReqTopicsSessionId
	(*reCtx.ReCtx)(nil),        // 1: reCtx.ReCtx
}
var file_toServer_reqTopicsSessionId_proto_depIdxs = []int32{
	1, // 0: toServerSubscribe.ReqTopicsSessionId.reCtx:type_name -> reCtx.ReCtx
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_toServer_reqTopicsSessionId_proto_init() }
func file_toServer_reqTopicsSessionId_proto_init() {
	if File_toServer_reqTopicsSessionId_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_toServer_reqTopicsSessionId_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqTopicsSessionId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_toServer_reqTopicsSessionId_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_toServer_reqTopicsSessionId_proto_goTypes,
		DependencyIndexes: file_toServer_reqTopicsSessionId_proto_depIdxs,
		MessageInfos:      file_toServer_reqTopicsSessionId_proto_msgTypes,
	}.Build()
	File_toServer_reqTopicsSessionId_proto = out.File
	file_toServer_reqTopicsSessionId_proto_rawDesc = nil
	file_toServer_reqTopicsSessionId_proto_goTypes = nil
	file_toServer_reqTopicsSessionId_proto_depIdxs = nil
}
