// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: toWorker/respTopicsConnCount.proto

package respTopicsConnCount

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reCtx "netsvr/internal/protocol/reCtx"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 返回网关中的某几个主题的连接数
type RespTopicsConnCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 请求上下文，网关会原样回传给工作进程
	ReCtx *reCtx.ReCtx `protobuf:"bytes,1,opt,name=reCtx,proto3" json:"reCtx,omitempty"`
	// key是topic，value是该主题的连接数
	// 如果topic没找到，则items中不会有该topic
	Items map[string]int32 `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *RespTopicsConnCount) Reset() {
	*x = RespTopicsConnCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toWorker_respTopicsConnCount_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespTopicsConnCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespTopicsConnCount) ProtoMessage() {}

func (x *RespTopicsConnCount) ProtoReflect() protoreflect.Message {
	mi := &file_toWorker_respTopicsConnCount_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespTopicsConnCount.ProtoReflect.Descriptor instead.
func (*RespTopicsConnCount) Descriptor() ([]byte, []int) {
	return file_toWorker_respTopicsConnCount_proto_rawDescGZIP(), []int{0}
}

func (x *RespTopicsConnCount) GetReCtx() *reCtx.ReCtx {
	if x != nil {
		return x.ReCtx
	}
	return nil
}

func (x *RespTopicsConnCount) GetItems() map[string]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_toWorker_respTopicsConnCount_proto protoreflect.FileDescriptor

var file_toWorker_respTopicsConnCount_proto_rawDesc = []byte{
	0x0a, 0x22, 0x74, 0x6f, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x74, 0x6f, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x1a, 0x11, 0x72, 0x65, 0x43, 0x74, 0x78, 0x2f, 0x72, 0x65,
	0x43, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbb, 0x01, 0x0a, 0x13, 0x52, 0x65,
	0x73, 0x70, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x22, 0x0a, 0x05, 0x72, 0x65, 0x43, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x72, 0x65, 0x43, 0x74, 0x78, 0x2e, 0x52, 0x65, 0x43, 0x74, 0x78, 0x52, 0x05,
	0x72, 0x65, 0x43, 0x74, 0x78, 0x12, 0x46, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x74, 0x6f, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x38, 0x0a,
	0x0a, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x4b, 0x5a, 0x49, 0x6e, 0x65, 0x74, 0x73, 0x76,
	0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2f, 0x74, 0x6f, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x73,
	0x70, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x3b, 0x72, 0x65, 0x73, 0x70, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_toWorker_respTopicsConnCount_proto_rawDescOnce sync.Once
	file_toWorker_respTopicsConnCount_proto_rawDescData = file_toWorker_respTopicsConnCount_proto_rawDesc
)

func file_toWorker_respTopicsConnCount_proto_rawDescGZIP() []byte {
	file_toWorker_respTopicsConnCount_proto_rawDescOnce.Do(func() {
		file_toWorker_respTopicsConnCount_proto_rawDescData = protoimpl.X.CompressGZIP(file_toWorker_respTopicsConnCount_proto_rawDescData)
	})
	return file_toWorker_respTopicsConnCount_proto_rawDescData
}

var file_toWorker_respTopicsConnCount_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_toWorker_respTopicsConnCount_proto_goTypes = []interface{}{
	(*RespTopicsConnCount)(nil), // 0: toWorkerTransfer.RespTopicsConnCount
	nil,                         // 1: toWorkerTransfer.RespTopicsConnCount.ItemsEntry
	(*reCtx.ReCtx)(nil),         // 2: reCtx.ReCtx
}
var file_toWorker_respTopicsConnCount_proto_depIdxs = []int32{
	2, // 0: toWorkerTransfer.RespTopicsConnCount.reCtx:type_name -> reCtx.ReCtx
	1, // 1: toWorkerTransfer.RespTopicsConnCount.items:type_name -> toWorkerTransfer.RespTopicsConnCount.ItemsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_toWorker_respTopicsConnCount_proto_init() }
func file_toWorker_respTopicsConnCount_proto_init() {
	if File_toWorker_respTopicsConnCount_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_toWorker_respTopicsConnCount_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespTopicsConnCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_toWorker_respTopicsConnCount_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_toWorker_respTopicsConnCount_proto_goTypes,
		DependencyIndexes: file_toWorker_respTopicsConnCount_proto_depIdxs,
		MessageInfos:      file_toWorker_respTopicsConnCount_proto_msgTypes,
	}.Build()
	File_toWorker_respTopicsConnCount_proto = out.File
	file_toWorker_respTopicsConnCount_proto_rawDesc = nil
	file_toWorker_respTopicsConnCount_proto_goTypes = nil
	file_toWorker_respTopicsConnCount_proto_depIdxs = nil
}
