# 日志级别 debug、info、warn、error
LogLevel = "debug"
# 网关服务唯一编号，取值范围是 uint8，会成为uniqId的前缀，16进制表示，占两个字符
ServerId = 0
# 网关收到停止信号后的等待时间，0表示永久等待，否则是超过这个时间还没优雅停止，则会强制退出
ShutdownWaitTime = "3s"
# pprof服务器监听的地址，ip:port，这个地址一般是内网地址，如果是空值，则不会开启
PprofListenAddress = "127.0.0.1:6062"
# business的限流器
Limit = [
    # 表示网关每秒最多向workerId为1的business转发1000次客户发送的数据或连接打开的数据
    { workerIds = [1], concurrency = 1000, name = "1" },
    # 表示网关每秒最多向workerId为{2,3,4,5}的这批business转发1000次客户发送的数据或连接打开的数据
    # 注意不是每个workerId都1000，而是这批workerId加起来才1000，因为这批workerId共用一个限流器
    { workerIds = [2, 3, 4, 5], concurrency = 1000, name = "2-5" }
]
# 客户服务器配置
[Customer]
# 监听的地址，ip:port，这个地址一般是外网地址
ListenAddress = "127.0.0.1:6060"
# url路由
HandlePattern = "/netsvr"
# 允许连接的origin，空表示不限制，否则会进行包含匹配
AllowOrigin = []
# 网关读取客户连接的超时时间，该时间段内，客户连接没有发消息过来，则会超时，连接会被关闭
ReadDeadline = "120s"
# 最大连接数，超过的会被拒绝
MaxOnlineNum = 100000
# 客户发送数据的大小限制（单位：字节）
ReceivePackLimit = 2097152
# 指定处理连接打开的worker id，允许设置为0，表示不关心连接的打开
ConnOpenWorkerId = 1
# 指定处理连接关闭的worker id，允许设置为0，表示不关心连接的关闭
ConnCloseWorkerId = 1
# tls配置
TLSCert = ""
TLSKey = ""

#worker服务器
[Worker]
# 监听的地址，ip:port，这个地址最好是内网地址，外网不允许访问
ListenAddress = "127.0.0.1:6061"
# worker读取business连接的超时时间，该时间段内，business连接没有发消息过来，则会超时，连接会被关闭
ReadDeadline = "120s"
# worker发送给business连接的超时时间，该时间段内，没发送成功，business连接会被关闭
SendDeadline = "10s"
# business发送数据的大小限制（单位：字节）
ReceivePackLimit = 2097152

# 统计服务
[Metrics]
# 统计服务的各种状态，空，则不统计任何状态
# 0：统计客户连接的打开情况，1：统计客户连接的关闭情况，2：统计客户连接的心跳情况，3：统计客户数据转发到worker的次数情况，4：统计客户数据转发到worker的字节数情况
Item = [0, 1, 2, 3, 4]
# 统计服务的各种状态里记录最大值的间隔时间
MaxRecordInterval = "10s"
