// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: toServer/router.proto

package router

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 工作进程，发给服务器的各种指令
type Cmd int32

const (
	// RegisterWorker 注册工作进程
	Cmd_RegisterWorker Cmd = 0
	// BroadCast 广播
	Cmd_BroadCast Cmd = 1
	// Multicast 组播
	Cmd_Multicast Cmd = 2
	// SingleCast 单播
	Cmd_SingleCast Cmd = 3
	// Subscribe 订阅
	Cmd_Subscribe Cmd = 4
	// Unsubscribe 取消订阅
	Cmd_Unsubscribe Cmd = 5
	// Publish 发布
	Cmd_Publish Cmd = 6
)

// Enum value maps for Cmd.
var (
	Cmd_name = map[int32]string{
		0: "RegisterWorker",
		1: "BroadCast",
		2: "Multicast",
		3: "SingleCast",
		4: "Subscribe",
		5: "Unsubscribe",
		6: "Publish",
	}
	Cmd_value = map[string]int32{
		"RegisterWorker": 0,
		"BroadCast":      1,
		"Multicast":      2,
		"SingleCast":     3,
		"Subscribe":      4,
		"Unsubscribe":    5,
		"Publish":        6,
	}
)

func (x Cmd) Enum() *Cmd {
	p := new(Cmd)
	*p = x
	return p
}

func (x Cmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cmd) Descriptor() protoreflect.EnumDescriptor {
	return file_toServer_router_proto_enumTypes[0].Descriptor()
}

func (Cmd) Type() protoreflect.EnumType {
	return &file_toServer_router_proto_enumTypes[0]
}

func (x Cmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cmd.Descriptor instead.
func (Cmd) EnumDescriptor() ([]byte, []int) {
	return file_toServer_router_proto_rawDescGZIP(), []int{0}
}

// 路由
type Router struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 命令
	Cmd Cmd `protobuf:"varint,1,opt,name=cmd,proto3,enum=toServerRouter.Cmd" json:"cmd,omitempty"`
	// 命令携带的数据
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Router) Reset() {
	*x = Router{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toServer_router_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Router) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Router) ProtoMessage() {}

func (x *Router) ProtoReflect() protoreflect.Message {
	mi := &file_toServer_router_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Router.ProtoReflect.Descriptor instead.
func (*Router) Descriptor() ([]byte, []int) {
	return file_toServer_router_proto_rawDescGZIP(), []int{0}
}

func (x *Router) GetCmd() Cmd {
	if x != nil {
		return x.Cmd
	}
	return Cmd_RegisterWorker
}

func (x *Router) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_toServer_router_proto protoreflect.FileDescriptor

var file_toServer_router_proto_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x74, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x22, 0x43, 0x0a, 0x06, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x12, 0x25, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13,
	0x2e, 0x74, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e,
	0x43, 0x6d, 0x64, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x74, 0x0a, 0x03,
	0x43, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x72, 0x6f, 0x61, 0x64,
	0x43, 0x61, 0x73, 0x74, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x63,
	0x61, 0x73, 0x74, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43,
	0x61, 0x73, 0x74, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x10, 0x06, 0x42, 0x23, 0x5a, 0x21, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x74, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72,
	0x3b, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_toServer_router_proto_rawDescOnce sync.Once
	file_toServer_router_proto_rawDescData = file_toServer_router_proto_rawDesc
)

func file_toServer_router_proto_rawDescGZIP() []byte {
	file_toServer_router_proto_rawDescOnce.Do(func() {
		file_toServer_router_proto_rawDescData = protoimpl.X.CompressGZIP(file_toServer_router_proto_rawDescData)
	})
	return file_toServer_router_proto_rawDescData
}

var file_toServer_router_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_toServer_router_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_toServer_router_proto_goTypes = []interface{}{
	(Cmd)(0),       // 0: toServerRouter.Cmd
	(*Router)(nil), // 1: toServerRouter.Router
}
var file_toServer_router_proto_depIdxs = []int32{
	0, // 0: toServerRouter.Router.cmd:type_name -> toServerRouter.Cmd
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_toServer_router_proto_init() }
func file_toServer_router_proto_init() {
	if File_toServer_router_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_toServer_router_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Router); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_toServer_router_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_toServer_router_proto_goTypes,
		DependencyIndexes: file_toServer_router_proto_depIdxs,
		EnumInfos:         file_toServer_router_proto_enumTypes,
		MessageInfos:      file_toServer_router_proto_msgTypes,
	}.Build()
	File_toServer_router_proto = out.File
	file_toServer_router_proto_rawDesc = nil
	file_toServer_router_proto_goTypes = nil
	file_toServer_router_proto_depIdxs = nil
}
