// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: netSvrStatusResp.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// worker响应网关的状态到business
type NetSvrStatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// req（request）、resp（response）时候的上下文，worker会原样回传给business
	ReCtx *ReCtx `protobuf:"bytes,1,opt,name=reCtx,proto3" json:"reCtx,omitempty"`
	// 网关中的客户连接数
	CustomerConnCount int32 `protobuf:"varint,2,opt,name=customerConnCount,proto3" json:"customerConnCount,omitempty"`
	// 网关中的主题数量
	TopicCount int32 `protobuf:"varint,3,opt,name=topicCount,proto3" json:"topicCount,omitempty"`
	// 等待转发到客户的数据量
	CatapultWaitSendCount int32 `protobuf:"varint,4,opt,name=catapultWaitSendCount,proto3" json:"catapultWaitSendCount,omitempty"`
	// 客户于发送数据给客户的协程数量
	CatapultConsumer int32 `protobuf:"varint,5,opt,name=catapultConsumer,proto3" json:"catapultConsumer,omitempty"`
	// 等待发送给客户数据的缓冲区的大小
	CatapultChanCap int32 `protobuf:"varint,6,opt,name=catapultChanCap,proto3" json:"catapultChanCap,omitempty"`
}

func (x *NetSvrStatusResp) Reset() {
	*x = NetSvrStatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netSvrStatusResp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetSvrStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetSvrStatusResp) ProtoMessage() {}

func (x *NetSvrStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_netSvrStatusResp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetSvrStatusResp.ProtoReflect.Descriptor instead.
func (*NetSvrStatusResp) Descriptor() ([]byte, []int) {
	return file_netSvrStatusResp_proto_rawDescGZIP(), []int{0}
}

func (x *NetSvrStatusResp) GetReCtx() *ReCtx {
	if x != nil {
		return x.ReCtx
	}
	return nil
}

func (x *NetSvrStatusResp) GetCustomerConnCount() int32 {
	if x != nil {
		return x.CustomerConnCount
	}
	return 0
}

func (x *NetSvrStatusResp) GetTopicCount() int32 {
	if x != nil {
		return x.TopicCount
	}
	return 0
}

func (x *NetSvrStatusResp) GetCatapultWaitSendCount() int32 {
	if x != nil {
		return x.CatapultWaitSendCount
	}
	return 0
}

func (x *NetSvrStatusResp) GetCatapultConsumer() int32 {
	if x != nil {
		return x.CatapultConsumer
	}
	return 0
}

func (x *NetSvrStatusResp) GetCatapultChanCap() int32 {
	if x != nil {
		return x.CatapultChanCap
	}
	return 0
}

var File_netSvrStatusResp_proto protoreflect.FileDescriptor

var file_netSvrStatusResp_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6e, 0x65, 0x74, 0x53, 0x76, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x6e, 0x65, 0x74, 0x73, 0x76, 0x72,
	0x2e, 0x6e, 0x65, 0x74, 0x53, 0x76, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x1a, 0x0b, 0x72, 0x65, 0x43, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97,
	0x02, 0x0a, 0x10, 0x4e, 0x65, 0x74, 0x53, 0x76, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x29, 0x0a, 0x05, 0x72, 0x65, 0x43, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x65, 0x74, 0x73, 0x76, 0x72, 0x2e, 0x72, 0x65, 0x43, 0x74,
	0x78, 0x2e, 0x52, 0x65, 0x43, 0x74, 0x78, 0x52, 0x05, 0x72, 0x65, 0x43, 0x74, 0x78, 0x12, 0x2c,
	0x0a, 0x11, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x34, 0x0a, 0x15,
	0x63, 0x61, 0x74, 0x61, 0x70, 0x75, 0x6c, 0x74, 0x57, 0x61, 0x69, 0x74, 0x53, 0x65, 0x6e, 0x64,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x15, 0x63, 0x61, 0x74,
	0x61, 0x70, 0x75, 0x6c, 0x74, 0x57, 0x61, 0x69, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x61, 0x74, 0x61, 0x70, 0x75, 0x6c, 0x74, 0x43, 0x6f,
	0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x63, 0x61,
	0x74, 0x61, 0x70, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x28,
	0x0a, 0x0f, 0x63, 0x61, 0x74, 0x61, 0x70, 0x75, 0x6c, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x43, 0x61,
	0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x63, 0x61, 0x74, 0x61, 0x70, 0x75, 0x6c,
	0x74, 0x43, 0x68, 0x61, 0x6e, 0x43, 0x61, 0x70, 0x42, 0x1c, 0x5a, 0x1a, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_netSvrStatusResp_proto_rawDescOnce sync.Once
	file_netSvrStatusResp_proto_rawDescData = file_netSvrStatusResp_proto_rawDesc
)

func file_netSvrStatusResp_proto_rawDescGZIP() []byte {
	file_netSvrStatusResp_proto_rawDescOnce.Do(func() {
		file_netSvrStatusResp_proto_rawDescData = protoimpl.X.CompressGZIP(file_netSvrStatusResp_proto_rawDescData)
	})
	return file_netSvrStatusResp_proto_rawDescData
}

var file_netSvrStatusResp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_netSvrStatusResp_proto_goTypes = []interface{}{
	(*NetSvrStatusResp)(nil), // 0: netsvr.netSvrStatusResp.NetSvrStatusResp
	(*ReCtx)(nil),            // 1: netsvr.reCtx.ReCtx
}
var file_netSvrStatusResp_proto_depIdxs = []int32{
	1, // 0: netsvr.netSvrStatusResp.NetSvrStatusResp.reCtx:type_name -> netsvr.reCtx.ReCtx
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_netSvrStatusResp_proto_init() }
func file_netSvrStatusResp_proto_init() {
	if File_netSvrStatusResp_proto != nil {
		return
	}
	file_reCtx_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_netSvrStatusResp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetSvrStatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_netSvrStatusResp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_netSvrStatusResp_proto_goTypes,
		DependencyIndexes: file_netSvrStatusResp_proto_depIdxs,
		MessageInfos:      file_netSvrStatusResp_proto_msgTypes,
	}.Build()
	File_netSvrStatusResp_proto = out.File
	file_netSvrStatusResp_proto_rawDesc = nil
	file_netSvrStatusResp_proto_goTypes = nil
	file_netSvrStatusResp_proto_depIdxs = nil
}
