// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: reCtx.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// req（request）、resp（response）时候的上下文，worker会原样回传给business
type ReCtx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 什么命令发起的请求，这个是business侧自定义的，网关不做任何加工处理
	Cmd int32 `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	// business发起请求的时候的具体上下文是什么，网关不做任何加工处理，比如可以携带当前客户的唯一id
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ReCtx) Reset() {
	*x = ReCtx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reCtx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReCtx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReCtx) ProtoMessage() {}

func (x *ReCtx) ProtoReflect() protoreflect.Message {
	mi := &file_reCtx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReCtx.ProtoReflect.Descriptor instead.
func (*ReCtx) Descriptor() ([]byte, []int) {
	return file_reCtx_proto_rawDescGZIP(), []int{0}
}

func (x *ReCtx) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *ReCtx) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_reCtx_proto protoreflect.FileDescriptor

var file_reCtx_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x65, 0x43, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6e,
	0x65, 0x74, 0x73, 0x76, 0x72, 0x2e, 0x72, 0x65, 0x43, 0x74, 0x78, 0x22, 0x2d, 0x0a, 0x05, 0x52,
	0x65, 0x43, 0x74, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x1c, 0x5a, 0x1a, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reCtx_proto_rawDescOnce sync.Once
	file_reCtx_proto_rawDescData = file_reCtx_proto_rawDesc
)

func file_reCtx_proto_rawDescGZIP() []byte {
	file_reCtx_proto_rawDescOnce.Do(func() {
		file_reCtx_proto_rawDescData = protoimpl.X.CompressGZIP(file_reCtx_proto_rawDescData)
	})
	return file_reCtx_proto_rawDescData
}

var file_reCtx_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_reCtx_proto_goTypes = []interface{}{
	(*ReCtx)(nil), // 0: netsvr.reCtx.ReCtx
}
var file_reCtx_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reCtx_proto_init() }
func file_reCtx_proto_init() {
	if File_reCtx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reCtx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReCtx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reCtx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reCtx_proto_goTypes,
		DependencyIndexes: file_reCtx_proto_depIdxs,
		MessageInfos:      file_reCtx_proto_msgTypes,
	}.Build()
	File_reCtx_proto = out.File
	file_reCtx_proto_rawDesc = nil
	file_reCtx_proto_goTypes = nil
	file_reCtx_proto_depIdxs = nil
}
