// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: sessionInfoResp.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// worker响应网关中的session信息到business
type SessionInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// req（request）、resp（response）时候的上下文，worker会原样回传给business
	ReCtx *ReCtx `protobuf:"bytes,1,opt,name=reCtx,proto3" json:"reCtx,omitempty"`
	// 连接的session id
	SessionId uint32 `protobuf:"varint,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	// 客户登录后，存储在网关中的信息，如果未登录或者登录了，但是没有设置，则是空字符串
	UserInfo string `protobuf:"bytes,3,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	// 客户在业务系统中的唯一id
	UserId string `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	// 客户是否登录成功
	LoginStatus bool `protobuf:"varint,5,opt,name=loginStatus,proto3" json:"loginStatus,omitempty"`
	// 客户订阅的主题
	Topics []string `protobuf:"bytes,6,rep,name=topics,proto3" json:"topics,omitempty"`
}

func (x *SessionInfoResp) Reset() {
	*x = SessionInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sessionInfoResp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfoResp) ProtoMessage() {}

func (x *SessionInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_sessionInfoResp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfoResp.ProtoReflect.Descriptor instead.
func (*SessionInfoResp) Descriptor() ([]byte, []int) {
	return file_sessionInfoResp_proto_rawDescGZIP(), []int{0}
}

func (x *SessionInfoResp) GetReCtx() *ReCtx {
	if x != nil {
		return x.ReCtx
	}
	return nil
}

func (x *SessionInfoResp) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *SessionInfoResp) GetUserInfo() string {
	if x != nil {
		return x.UserInfo
	}
	return ""
}

func (x *SessionInfoResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionInfoResp) GetLoginStatus() bool {
	if x != nil {
		return x.LoginStatus
	}
	return false
}

func (x *SessionInfoResp) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

var File_sessionInfoResp_proto protoreflect.FileDescriptor

var file_sessionInfoResp_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x6e, 0x65, 0x74, 0x73, 0x76, 0x72, 0x2e,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x1a,
	0x0b, 0x72, 0x65, 0x43, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc8, 0x01, 0x0a,
	0x0f, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x29, 0x0a, 0x05, 0x72, 0x65, 0x43, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x6e, 0x65, 0x74, 0x73, 0x76, 0x72, 0x2e, 0x72, 0x65, 0x43, 0x74, 0x78, 0x2e, 0x52,
	0x65, 0x43, 0x74, 0x78, 0x52, 0x05, 0x72, 0x65, 0x43, 0x74, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x42, 0x1c, 0x5a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sessionInfoResp_proto_rawDescOnce sync.Once
	file_sessionInfoResp_proto_rawDescData = file_sessionInfoResp_proto_rawDesc
)

func file_sessionInfoResp_proto_rawDescGZIP() []byte {
	file_sessionInfoResp_proto_rawDescOnce.Do(func() {
		file_sessionInfoResp_proto_rawDescData = protoimpl.X.CompressGZIP(file_sessionInfoResp_proto_rawDescData)
	})
	return file_sessionInfoResp_proto_rawDescData
}

var file_sessionInfoResp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sessionInfoResp_proto_goTypes = []interface{}{
	(*SessionInfoResp)(nil), // 0: netsvr.sessionInfoResp.SessionInfoResp
	(*ReCtx)(nil),           // 1: netsvr.reCtx.ReCtx
}
var file_sessionInfoResp_proto_depIdxs = []int32{
	1, // 0: netsvr.sessionInfoResp.SessionInfoResp.reCtx:type_name -> netsvr.reCtx.ReCtx
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sessionInfoResp_proto_init() }
func file_sessionInfoResp_proto_init() {
	if File_sessionInfoResp_proto != nil {
		return
	}
	file_reCtx_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_sessionInfoResp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sessionInfoResp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sessionInfoResp_proto_goTypes,
		DependencyIndexes: file_sessionInfoResp_proto_depIdxs,
		MessageInfos:      file_sessionInfoResp_proto_msgTypes,
	}.Build()
	File_sessionInfoResp_proto = out.File
	file_sessionInfoResp_proto_rawDesc = nil
	file_sessionInfoResp_proto_goTypes = nil
	file_sessionInfoResp_proto_depIdxs = nil
}
