// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: topicsUniqIdCountResp.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// worker响应business，返回网关中的主题包含的连接数
type TopicsUniqIdCountResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// worker原样回传给business
	CtxData []byte `protobuf:"bytes,1,opt,name=ctxData,proto3" json:"ctxData,omitempty"`
	// key是topic，value是该主题的连接数
	// 如果topic没找到，则items中不会有该topic
	Items map[string]int32 `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *TopicsUniqIdCountResp) Reset() {
	*x = TopicsUniqIdCountResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topicsUniqIdCountResp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicsUniqIdCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicsUniqIdCountResp) ProtoMessage() {}

func (x *TopicsUniqIdCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_topicsUniqIdCountResp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicsUniqIdCountResp.ProtoReflect.Descriptor instead.
func (*TopicsUniqIdCountResp) Descriptor() ([]byte, []int) {
	return file_topicsUniqIdCountResp_proto_rawDescGZIP(), []int{0}
}

func (x *TopicsUniqIdCountResp) GetCtxData() []byte {
	if x != nil {
		return x.CtxData
	}
	return nil
}

func (x *TopicsUniqIdCountResp) GetItems() map[string]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_topicsUniqIdCountResp_proto protoreflect.FileDescriptor

var file_topicsUniqIdCountResp_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x55, 0x6e, 0x69, 0x71, 0x49, 0x64, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x6e,
	0x65, 0x74, 0x73, 0x76, 0x72, 0x2e, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x55, 0x6e, 0x69, 0x71,
	0x49, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0xc1, 0x01, 0x0a, 0x15,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x55, 0x6e, 0x69, 0x71, 0x49, 0x64, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x74, 0x78, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x74, 0x78, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x54, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3e,
	0x2e, 0x6e, 0x65, 0x74, 0x73, 0x76, 0x72, 0x2e, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x55, 0x6e,
	0x69, 0x71, 0x49, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x54, 0x6f,
	0x70, 0x69, 0x63, 0x73, 0x55, 0x6e, 0x69, 0x71, 0x49, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42,
	0x1c, 0x5a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_topicsUniqIdCountResp_proto_rawDescOnce sync.Once
	file_topicsUniqIdCountResp_proto_rawDescData = file_topicsUniqIdCountResp_proto_rawDesc
)

func file_topicsUniqIdCountResp_proto_rawDescGZIP() []byte {
	file_topicsUniqIdCountResp_proto_rawDescOnce.Do(func() {
		file_topicsUniqIdCountResp_proto_rawDescData = protoimpl.X.CompressGZIP(file_topicsUniqIdCountResp_proto_rawDescData)
	})
	return file_topicsUniqIdCountResp_proto_rawDescData
}

var file_topicsUniqIdCountResp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_topicsUniqIdCountResp_proto_goTypes = []interface{}{
	(*TopicsUniqIdCountResp)(nil), // 0: netsvr.topicsUniqIdCountResp.TopicsUniqIdCountResp
	nil,                           // 1: netsvr.topicsUniqIdCountResp.TopicsUniqIdCountResp.ItemsEntry
}
var file_topicsUniqIdCountResp_proto_depIdxs = []int32{
	1, // 0: netsvr.topicsUniqIdCountResp.TopicsUniqIdCountResp.items:type_name -> netsvr.topicsUniqIdCountResp.TopicsUniqIdCountResp.ItemsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_topicsUniqIdCountResp_proto_init() }
func file_topicsUniqIdCountResp_proto_init() {
	if File_topicsUniqIdCountResp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_topicsUniqIdCountResp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicsUniqIdCountResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_topicsUniqIdCountResp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_topicsUniqIdCountResp_proto_goTypes,
		DependencyIndexes: file_topicsUniqIdCountResp_proto_depIdxs,
		MessageInfos:      file_topicsUniqIdCountResp_proto_msgTypes,
	}.Build()
	File_topicsUniqIdCountResp_proto = out.File
	file_topicsUniqIdCountResp_proto_rawDesc = nil
	file_topicsUniqIdCountResp_proto_goTypes = nil
	file_topicsUniqIdCountResp_proto_depIdxs = nil
}
