// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: updateInfo.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 更新连接的info信息
type UpdateInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 目标uniqId
	UniqId string `protobuf:"bytes,1,opt,name=uniqId,proto3" json:"uniqId,omitempty"`
	// 最新的uniqId，传递了则覆盖
	NewUniqId string `protobuf:"bytes,2,opt,name=NewUniqId,proto3" json:"NewUniqId,omitempty"`
	// 最新的session，传递了则覆盖
	NewSession string `protobuf:"bytes,3,opt,name=NewSession,proto3" json:"NewSession,omitempty"`
	// 最新的主题，传递了则覆盖
	NewTopics []string `protobuf:"bytes,4,rep,name=NewTopics,proto3" json:"NewTopics,omitempty"`
	// 需要发给客户的数据，传递了则转发给客户
	Data []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateInfo) Reset() {
	*x = UpdateInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_updateInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInfo) ProtoMessage() {}

func (x *UpdateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_updateInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInfo.ProtoReflect.Descriptor instead.
func (*UpdateInfo) Descriptor() ([]byte, []int) {
	return file_updateInfo_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateInfo) GetUniqId() string {
	if x != nil {
		return x.UniqId
	}
	return ""
}

func (x *UpdateInfo) GetNewUniqId() string {
	if x != nil {
		return x.NewUniqId
	}
	return ""
}

func (x *UpdateInfo) GetNewSession() string {
	if x != nil {
		return x.NewSession
	}
	return ""
}

func (x *UpdateInfo) GetNewTopics() []string {
	if x != nil {
		return x.NewTopics
	}
	return nil
}

func (x *UpdateInfo) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_updateInfo_proto protoreflect.FileDescriptor

var file_updateInfo_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x11, 0x6e, 0x65, 0x74, 0x73, 0x76, 0x72, 0x2e, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x94, 0x01, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x4e, 0x65, 0x77, 0x55, 0x6e, 0x69, 0x71, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x4e, 0x65, 0x77, 0x55, 0x6e, 0x69, 0x71, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x4e, 0x65,
	0x77, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x4e, 0x65, 0x77, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x65,
	0x77, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x4e,
	0x65, 0x77, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x1c, 0x5a, 0x1a,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_updateInfo_proto_rawDescOnce sync.Once
	file_updateInfo_proto_rawDescData = file_updateInfo_proto_rawDesc
)

func file_updateInfo_proto_rawDescGZIP() []byte {
	file_updateInfo_proto_rawDescOnce.Do(func() {
		file_updateInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_updateInfo_proto_rawDescData)
	})
	return file_updateInfo_proto_rawDescData
}

var file_updateInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_updateInfo_proto_goTypes = []interface{}{
	(*UpdateInfo)(nil), // 0: netsvr.updateInfo.UpdateInfo
}
var file_updateInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_updateInfo_proto_init() }
func file_updateInfo_proto_init() {
	if File_updateInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_updateInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_updateInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_updateInfo_proto_goTypes,
		DependencyIndexes: file_updateInfo_proto_depIdxs,
		MessageInfos:      file_updateInfo_proto_msgTypes,
	}.Build()
	File_updateInfo_proto = out.File
	file_updateInfo_proto_rawDesc = nil
	file_updateInfo_proto_goTypes = nil
	file_updateInfo_proto_depIdxs = nil
}
