// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: api/transferToWorker.proto

package transferToWorker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 转发客户的信息到工作进程
type TransferToWorker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 当前连接的id
	SessionId uint32 `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	// 当前连接发过来的数据
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *TransferToWorker) Reset() {
	*x = TransferToWorker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_transferToWorker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferToWorker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferToWorker) ProtoMessage() {}

func (x *TransferToWorker) ProtoReflect() protoreflect.Message {
	mi := &file_api_transferToWorker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferToWorker.ProtoReflect.Descriptor instead.
func (*TransferToWorker) Descriptor() ([]byte, []int) {
	return file_api_transferToWorker_proto_rawDescGZIP(), []int{0}
}

func (x *TransferToWorker) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *TransferToWorker) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_transferToWorker_proto protoreflect.FileDescriptor

var file_api_transferToWorker_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x54, 0x6f,
	0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x44, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x54, 0x6f, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x2e, 0x5a, 0x2c,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x54, 0x6f, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x3b, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x54, 0x6f, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_transferToWorker_proto_rawDescOnce sync.Once
	file_api_transferToWorker_proto_rawDescData = file_api_transferToWorker_proto_rawDesc
)

func file_api_transferToWorker_proto_rawDescGZIP() []byte {
	file_api_transferToWorker_proto_rawDescOnce.Do(func() {
		file_api_transferToWorker_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_transferToWorker_proto_rawDescData)
	})
	return file_api_transferToWorker_proto_rawDescData
}

var file_api_transferToWorker_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_transferToWorker_proto_goTypes = []interface{}{
	(*TransferToWorker)(nil), // 0: protocol.TransferToWorker
}
var file_api_transferToWorker_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_transferToWorker_proto_init() }
func file_api_transferToWorker_proto_init() {
	if File_api_transferToWorker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_transferToWorker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferToWorker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_transferToWorker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_transferToWorker_proto_goTypes,
		DependencyIndexes: file_api_transferToWorker_proto_depIdxs,
		MessageInfos:      file_api_transferToWorker_proto_msgTypes,
	}.Build()
	File_api_transferToWorker_proto = out.File
	file_api_transferToWorker_proto_rawDesc = nil
	file_api_transferToWorker_proto_goTypes = nil
	file_api_transferToWorker_proto_depIdxs = nil
}
